---
title: "What is the expected duration (in years) of your current position (in total)?"
question_id: currentEmp11_0
---

```{r}
#| include: false
#| file: ../R/_load_common.R
```

```{r}
#| echo: false
question_code <- "currentEmp11_0"

```

## `r filter_label`

### Descriptive Statistics

```{r}
#| echo: false

print_heatmap_category_table(
  FILTER,
  question_code,
  header = paste0("Expected position duration (", filter_label, ")")
)
```

```{r}
#| echo: false
#| fig-width: 10
#| fig-height: 6

plot_heatmap_category_barplot(
  FILTER,
  question_code,
  title = paste0("Expected position duration (", filter_label, ")")
)
```

### Statistics by age group

```{r}
#| echo: false

print_heatmap_category_age_wide_table(
  FILTER,
  question_code,
  header = paste0("Expected position duration by age group (", filter_label, ")")
)
```

```{r}
#| echo: false
#| results: asis
#| eval: !expr show_within
cat("## Within ", filter_label, "

", sep = "")
```


```{r}
#| eval: !expr show_within
#| echo: false

print_heatmap_category_table(
  FILTER,
  question_code,
  header = paste0("Expected position duration within ", filter_label),
  group_by = FILTER
)
```

```{r}
#| eval: !expr show_within
#| echo: false
#| fig-width: 10
#| fig-height: 6

plot_heatmap_category_stacked_bars(
  FILTER,
  question_code,
  countries = FILTER,
  title = paste0("Expected position duration within ", filter_label)
)
```

## Between Countries

```{r}
#| echo: false
#| fig-width: 10
#| fig-height: 6

plot_heatmap_category_stacked_bars(
  plot_countries,
  question_code,
  country_groups = country_groups,
  title = "Expected position duration by country group"
)
```
