---
title: "What is the minimum number of software developers that would have to suddenly disappear from your current project before it stalls due to a lack of knowledgeable people?"
question_id: stability1_0
---

```{r}
#| include: false
#| file: ../R/_load_common.R
```

```{r}
#| echo: false
question_code <- "stability1_0"

nordic_countries <- c(
  "Finland", "Norway", "Sweden", "Denmark", "Iceland", "Estonia"
)
country_groups <- list(
  Nordics = nordic_countries,
  Germany = "Germany",
  Netherlands = "Netherlands"
)
plot_countries <- countries_from_groups(country_groups)
```

## Nordics

### Descriptive Statistics

```{r}
#| echo: false

print_heatmap_category_table(
  FILTER,
  question_code,
  header = "What is the minimum number of software developers that would have to suddenly disappear from your current project before it stalls due to a lack of knowledgeable people? (Nordics)"
)
```

```{r}
#| echo: false
#| fig-width: 10
#| fig-height: 8

plot_heatmap_category_barplot(
  FILTER,
  question_code,
  title = "What is the minimum number of software developers that would have to suddenly disappear from your current project before it stalls due to a lack of knowledgeable people? (Nordics)"
)
```

### Statistics by age group

```{r}
#| echo: false

print_heatmap_category_age_wide_table(
  FILTER,
  question_code,
  header = "What is the minimum number of software developers that would have to suddenly disappear from your current project before it stalls due to a lack of knowledgeable people? by age group (Nordics)"
)
```

## Within Nordics

```{r}
#| echo: false

print_heatmap_category_table(
  nordic_countries,
  question_code,
  header = "What is the minimum number of software developers that would have to suddenly disappear from your current project before it stalls due to a lack of knowledgeable people? within Nordic countries",
  group_by = nordic_countries
)
```

```{r}
#| echo: false
#| fig-width: 10
#| fig-height: 8

plot_heatmap_category_stacked_bars(
  nordic_countries,
  question_code,
  countries = nordic_countries,
  title = "What is the minimum number of software developers that would have to suddenly disappear from your current project before it stalls due to a lack of knowledgeable people? within Nordic countries"
)
```

## Between Countries

```{r}
#| echo: false
#| fig-width: 10
#| fig-height: 8

plot_heatmap_category_stacked_bars(
  plot_countries,
  question_code,
  country_groups = country_groups,
  title = "What is the minimum number of software developers that would have to suddenly disappear from your current project before it stalls due to a lack of knowledgeable people? by country group"
)
```
