genAI6_0_recode_map <- tibble::tribble(
  ~raw, ~clean,
  # --- Exclusions ---
  "^without them$",
  NA_character_,
  # --- Broad / baseline software engineering (early; may be overridden below) ---
  "(?i)\\b(software engineering|knowledge of software)\\b",
  "Foundational software engineering skills",
  "(?i)same as (now|normal rs work)|which requires research and programming skills",
  "Foundational software engineering skills",
  "(?i)\\b(fundamental knowledge about research software dev|good engineering skill|previous coding experience)\\b",
  "Foundational software engineering skills",
  "(?i)knowing how to do the job without genai|development without generative ai",
  "Foundational software engineering skills",
  "(?i)you need to already be a good well rounded developer",
  "Foundational software engineering skills",
  # --- Software architecture ---
  "(?i)\\b(architechture understanding|software architecture|system architecture planning)\\b",
  "Software architecture and system design",
  "(?i)understanding of how parts go together",
  "Software architecture and system design",
  # --- Testing / QA ---
  "(?i)^(testing|qa and testing)$",
  "Testing, QA and verification",
  "(?i)\\bhow to verify code\\b|formal validation methods",
  "Testing, QA and verification",
  # --- Documentation ---
  "(?i)^documentation$",
  "Software documentation",
  # --- DevOps / infrastructure ---
  "(?i)^devops$",
  "DevOps, cloud, HPC and data engineering",
  "(?i)knowledge about (cloud platforms|hpc)|strong data engineering fundamentals",
  "DevOps, cloud, HPC and data engineering",
  # --- Project management ---
  "(?i)\\b(project management|software project management)\\b",
  "Project and workflow management",
  # --- Communication ---
  "(?i)^communication$",
  "Communication and collaboration",
  # --- Domain / use-case understanding ---
  "(?i)background understanding of the use case",
  "Domain and use-case understanding",
  "(?i)understand the problem you.re trying to make it solve",
  "Domain and use-case understanding",
  "(?i)understanding (important concepts|of basics)",
  "Domain and use-case understanding",
  # --- Continuous learning / research ---
  "(?i)\\b(motivation to learn|following up with learning/research|research methodology)\\b",
  "Continuous learning and research practice",
  # --- Programming language / code literacy ---
  "(?i)\\b(code fluency|code understanding|reading/writing)\\b",
  "Programming language and code comprehension",
  "(?i)reasonable grasp of the programming language",
  "Programming language and code comprehension",
  "(?i)one needs to know how to at least read code",
  "Programming language and code comprehension",
  "(?i)conocimiento.*lenguaje",
  "Programming language and code comprehension",
  "(?i)understanding of the technology the ai is producing output for",
  "Programming language and code comprehension",
  # --- Prompt engineering / GenAI literacy ---
  "(?i)\\b(prompt(ing)? engineering|prompt enigneering|structured prompting|how to prompt well|good prompt engineering)\\b",
  "Prompt engineering and generative AI literacy",
  "(?i)\\b(llm knowledge|knowledge of ai tools)\\b",
  "Prompt engineering and generative AI literacy",
  "(?i)fundamental knowledge about generative ai",
  "Prompt engineering and generative AI literacy",
  "(?i)understanding of (what ai is attempting to do|flow to get most out of tools)",
  "Prompt engineering and generative AI literacy",
  "(?i)how to use(/prompt)? ai tools efficiently|keeping up to date on genai tools",
  "Prompt engineering and generative AI literacy",
  "(?i)choosing energy-cheap models",
  "Prompt engineering and generative AI literacy",
  # --- Critical thinking / scepticism ---
  "(?i)^(critical thinking|pensamiento cr[ií]tico)$",
  "Critical thinking, scepticism and output validation",
  "(?i)\\b(critical (eye|reading|sense)|sceptici[sz]m|sceptisisim|sound scepticism|common sense)\\b",
  "Critical thinking, scepticism and output validation",
  "(?i)reading/using with a [\"']?critical[\"']? lense",
  "Critical thinking, scepticism and output validation",
  "(?i)you need to be critical of what it outputs",
  "Critical thinking, scepticism and output validation",
  "(?i)vibe-coders are working blindly",
  "Critical thinking, scepticism and output validation",
  # --- Code review / fact-checking ---
  "(?i)\\b(code reviewing|reviewing|fact checking)\\b",
  "Code review, fact-checking and quality control",
  "(?i)workflows that mitigate slop",
  "Code review, fact-checking and quality control",
  # --- Judgement on AI use ---
  "(?i)\\bwhen to (not )?use\\b|to know when to use it and when not",
  "Judgement on when and how to use AI",
  "(?i)knowing what tasks to delegate",
  "Judgement on when and how to use AI",
  "(?i)restraint\\. limit ai use",
  "Judgement on when and how to use AI",
  "(?i)\\b(humility|taste)\\b",
  "Judgement on when and how to use AI",
  "(?i)the ability to look the other way",
  "Judgement on when and how to use AI",
  "(?i)how to use ai-generated results efficiently and safely",
  "Judgement on when and how to use AI",
  "(?i)good examples that shows possibilities and limitations",
  "Judgement on when and how to use AI",
  # --- Problem decomposition / planning ---
  "(?i)ability to break a problem down into smaller problems",
  "Problem decomposition, planning and algorithms",
  "(?i)^planning$",
  "Problem decomposition, planning and algorithms",
  "(?i)solid algorithmic idea",
  "Problem decomposition, planning and algorithms",
  # --- Security / ethics ---
  "(?i)\\b(ai ethics|notion of basic security caveats)\\b",
  "Security awareness and AI ethics",
  "(?i)understand security issues that can arise",
  "Security awareness and AI ethics",
  # --- Specific composite / truncated responses (late; override broad rules) ---
  "(?i)software development skills \\(version control",
  "Foundational software engineering skills",
  "(?i)management\\)\\. ability to understand information sources",
  "Project and workflow management",
  "(?i)proper prompting; understanding of llms; proper knowledge of programming languages",
  "Prompt engineering and generative AI literacy",
  "(?i)you would still need to have solid understanding of the software development process and architecture",
  "Foundational software engineering skills",
  "(?i)understand security issues that can arise\\. software engineering and architecture are still prerequisites",
  "Security awareness and AI ethics"
)
